[Unit]
PartOf=vpp.service ly-route-policy-routing.service
After=ly-route-policy-routing.service ly-route-control-api.service
Wants=ly-route-control-api.service
Wants=ly-route-dns-vpp-session.service
Before=ly-route-dns-vpp-session.service

[Service]
ExecStartPre=/usr/lib/ly-route/dns-ipset-sync.py --prepare
