unix {
  nodaemon
  log /var/log/vpp/vpp.log
  cli-listen /run/vpp/cli.sock
  gid vpp
}

api-segment {
  gid vpp
}

socksvr {
  default
}

session {
  enable rt-backend rule-table
}

cpu {
  workers 0
}

buffers {
  buffers-per-numa 4096
}

plugins {
  plugin linux_cp_plugin.so { enable }
  plugin linux_nl_plugin.so { enable }
}
