unix {
  nodaemon
  log /var/log/vpp/vpp.log
  cli-listen /run/vpp/cli.sock
  runtime-dir /run/vpp
  gid vpp
}

api-segment {
  gid vpp
}

socksvr {
  default
}

session {
  enable rt-backend rule-table
  use-app-socket-api
}

cpu {
  workers 0
}

buffers {
  buffers-per-numa 4096
}

plugins {
  plugin dpdk_plugin.so { disable }
  plugin linux_cp_plugin.so { enable }
  plugin linux_nl_plugin.so { enable }
}
